name: CI/CD - Staging

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    name: Build (CI)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: diegoweb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
          retention-days: 7

  deploy:
    name: Deploy to Staging (CD)
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: diegoweb

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: ${{ secrets.AWS_REGION_STAGING }}

      - name: Deploy to S3 (staging)
        run: aws s3 sync build/ s3://${{ secrets.STAGING_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CF_DISTRIBUTION_ID }} --paths "/*"
